global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django'
    scheme: https
    static_configs:
      - targets: ['paragoni.space']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    honor_labels: true
    tls_config:
      insecure_skip_verify: true

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']