[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/migrations/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
skip = ["migrations"]
skip_glob = ["**/migrations/*.py"] 