# Generated by Django 5.1.4 on 2024-12-13 09:24

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
    ]
