# Generated by Django 5.1.4 on 2024-12-09 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_movies', through='users.UserFavoriteMovie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'release_year'], name='movies_movi_title_1b2d98_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['director', 'release_year'], name='movies_movi_directo_5277e3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['movement', 'release_year'], name='movies_movi_movemen_335410_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['average_rating', 'release_year'], name='movies_movi_average_964eba_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_year', '-average_rating'], name='movies_movi_release_164bb1_idx'),
        ),
    ]
