name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      DEBUG: 'False'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      DB_HOST: db
      DB_PORT: 5432
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libpq-dev python3-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Run tests
      run: |
        echo "Starting tests with CI configuration..."
        export TEST_DB_PASSWORD="${{ secrets.TEST_DB_PASSWORD }}"
        export SECRET_KEY="${{ secrets.SECRET_KEY }}"
        docker-compose -f docker-compose.ci.yml config
        docker-compose -f docker-compose.ci.yml up -d db redis
        
        # Wait for DB to be ready
        echo "Waiting for database to be ready..."
        for i in {1..30}; do
          if docker-compose -f docker-compose.ci.yml exec -T db pg_isready -U postgres; then
            echo "Database is ready"
            break
          fi
          echo "Waiting... ($i/30)"
          sleep 1
        done
        
        # Clean up any existing test database and connections
        echo "Cleaning up existing connections..."
        docker-compose -f docker-compose.ci.yml exec -T db psql -U postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname IN ('postgres', 'test_postgres');" || true
        docker-compose -f docker-compose.ci.yml exec -T db psql -U postgres -c "DROP DATABASE IF EXISTS test_postgres WITH (FORCE);" || true
        
        # Run tests
        docker-compose -f docker-compose.ci.yml run --rm web python manage.py test --settings=config.test_settings
        TEST_EXIT_CODE=$?
        
        # Clean up after tests
        echo "Cleaning up after tests..."
        docker-compose -f docker-compose.ci.yml exec -T db psql -U postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname IN ('postgres', 'test_postgres');" || true
        docker-compose -f docker-compose.ci.yml exec -T db psql -U postgres -c "DROP DATABASE IF EXISTS test_postgres WITH (FORCE);" || true
        
        exit $TEST_EXIT_CODE
      env:
        DEBUG: 'False'
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        DB_HOST: db
        DB_PORT: 5432
        TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        DJANGO_SETTINGS_MODULE: config.test_settings

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Debug SSH Setup
      run: |
        echo "Setting up SSH debugging..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        echo "Known hosts file created"
        ls -la ~/.ssh
        cat ~/.ssh/known_hosts

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.SERVER_KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Verify SSH Connection
      run: |
        echo "Testing SSH connection..."
        ssh -v -T ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: db
        DB_PORT: ${{ secrets.DB_PORT }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        debug: true
        envs: SECRET_KEY,DB_NAME,DB_USER,DB_PASSWORD,DB_HOST,DB_PORT,ALLOWED_HOSTS,DJANGO_SUPERUSER_USERNAME,DJANGO_SUPERUSER_EMAIL,DJANGO_SUPERUSER_PASSWORD,GRAFANA_ADMIN_PASSWORD,DOCKERHUB_USERNAME,DOCKERHUB_TOKEN,TEST_DB_PASSWORD,GH_PAT
        script: |
          set -e
          echo "Starting deployment process..."
          
          # Create project directory if it doesn't exist
          mkdir -p /home/root/movie_rating_platform
          cd /home/root/movie_rating_platform
          
          # Configure Git
          git config --global user.email "deploy@paragoni.space"
          git config --global user.name "Deploy Bot"
          
          # Store credentials securely
          git config --global credential.helper store
          echo "https://maria-v-ch:${GH_PAT}@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials
          
          # Initialize git repository if needed
          if [ ! -d .git ]; then
            git init
            git config --global init.defaultBranch main
            git remote add origin https://github.com/maria-v-ch/movie-rating-platform.git
          else
            # Update origin if it exists
            git remote set-url origin https://github.com/maria-v-ch/movie-rating-platform.git
          fi
          
          # Pull latest changes
          git fetch origin main
          git reset --hard origin/main
          
          echo "Current directory: $(pwd)"

          # Create logs directory and set permissions
          mkdir -p logs
          chmod 777 logs
          echo "Created logs directory with appropriate permissions"

          # Install required packages
          echo "Updating package lists..."
          for i in {1..3}; do
              if sudo apt-get update; then
                  break
              fi
              echo "Package list update attempt $i failed, retrying..."
              sleep 10
          done

          echo "Installing required packages..."
          for i in {1..3}; do
              if DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends gettext-base; then
                  break
              fi
              echo "Package installation attempt $i failed, retrying..."
              sleep 10
          done

          # Stop Apache if it's running to free up ports 80 and 443
          echo "Stopping Apache service if running..."
          sudo systemctl stop apache2 || true
          sudo systemctl disable apache2 || true

          # Create .env file with environment variables
          cat > .env << EOL
          DEBUG=False
          SECRET_KEY=${SECRET_KEY}
          ALLOWED_HOSTS=${ALLOWED_HOSTS}
          CSRF_TRUSTED_ORIGINS=https://paragoni.space,https://www.paragoni.space
          CSRF_COOKIE_SECURE=True
          CSRF_COOKIE_HTTPONLY=False
          CSRF_USE_SESSIONS=False
          CSRF_COOKIE_SAMESITE=Lax
          DB_NAME=${DB_NAME}
          DB_USER=${DB_USER}
          DB_PASSWORD=${DB_PASSWORD}
          DB_HOST=db
          DB_PORT=${DB_PORT}
          DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
          DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
          DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
          GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
          EOL

          # Substitute environment variables in .env file
          envsubst < .env > .env.tmp && mv .env.tmp .env
          chmod 600 .env
          echo "Created .env file"

          # Login to Docker Hub
          echo "${DOCKERHUB_TOKEN}" | docker login -u ${DOCKERHUB_USERNAME} --password-stdin

          # Stop and remove existing containers
          echo "Stopping and removing existing containers..."
          sudo docker-compose down -v

          # Pull the latest images
          sudo docker-compose pull

          # Build and start the services
          echo "Starting services with detailed logging..."
          sudo docker-compose up -d --build

          # Function to check container health
          check_container_health() {
            local container=$1
            local max_attempts=$2
            local attempt=1
            
            echo "Checking health of $container container..."
            while [ $attempt -le $max_attempts ]; do
              if sudo docker-compose ps $container | grep -q "Up"; then
                echo "$container is running"
                return 0
              fi
              echo "Waiting for $container... (Attempt $attempt/$max_attempts)"
              sudo docker-compose logs --tail=50 $container
              attempt=$((attempt + 1))
              sleep 20
            done
            echo "$container failed to start properly"
            return 1
          }

          # Start and check database first
          echo "Starting database container..."
          sudo docker-compose up -d db
          if ! check_container_health "db" 15; then
            echo "Database failed to start. Deployment failed."
            exit 1
          fi

          # Start Redis
          echo "Starting Redis container..."
          sudo docker-compose up -d redis
          if ! check_container_health "redis" 10; then
            echo "Redis failed to start. Deployment failed."
            exit 1
          fi

          # Start web application
          echo "Starting web container..."
          sudo docker-compose up -d web
          if ! check_container_health "web" 20; then
            echo "Web container failed to start. Checking logs..."
            sudo docker-compose logs --tail=100 web
            exit 1
          fi

          # Start Nginx last
          echo "Starting Nginx container..."
          sudo docker-compose up -d nginx
          echo "Checking Nginx container status..."
          sudo docker-compose ps nginx
          echo "Checking Nginx logs..."
          sudo docker-compose logs --tail=100 nginx
          echo "Verifying Nginx configuration..."
          sudo docker-compose exec -T nginx nginx -t || true
          echo "Checking if Nginx is listening..."
          sudo docker-compose exec -T nginx curl -v localhost/health/ || true
          
          if ! check_container_health "nginx" 10; then
            echo "Nginx failed to start. Detailed diagnostics:"
            echo "1. Container Status:"
            sudo docker-compose ps nginx
            echo "2. Container Logs:"
            sudo docker-compose logs --tail=100 nginx
            echo "3. Nginx Configuration Test:"
            sudo docker-compose exec -T nginx nginx -t || true
            echo "4. Network Status:"
            sudo docker network ls
            sudo docker network inspect movie_rating_platform_app_network
            exit 1
          fi

          echo "All containers are running. Checking overall system health..."
          sudo docker-compose ps
          
          # Run migrations
          echo "Running database migrations..."
          if ! sudo docker-compose exec -T web python manage.py migrate; then
            echo "Migration failed. Checking database connection..."
            sudo docker-compose exec -T web python manage.py dbshell
            exit 1
          fi

          # Collect static files
          echo "Collecting static files..."
          if ! sudo docker-compose exec -T web python manage.py collectstatic --noinput; then
            echo "Static file collection failed. Checking permissions..."
            sudo docker-compose exec -T web ls -la /app/staticfiles
            exit 1
          fi

          echo "Deployment completed successfully!"
          echo "Final container status:"
          sudo docker-compose ps
          echo "Service logs:"
          sudo docker-compose logs --tail=20